/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Url = string;
/**
 * The international 2-letter country code as defined by the ISO 3166-1 standard.
 */
export type CountryCode = string;
/**
 * List of billing countries by identifier and label.
 */
export type StateCountry = {
  value: CountryCode;
  /**
   * Name of the country.
   */
  label: string;
}[];
/**
 * List of shipping countries by identifier and label.
 */
export type StateCountry1 = {
  value: CountryCode;
  /**
   * Name of the country.
   */
  label: string;
}[];
/**
 * List of shipping countries by identifier and label.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 */
export type StateCountry2 = {
  value: CountryCode;
  /**
   * Name of the country.
   */
  label: string;
}[];
/**
 * List of shipping countries by identifier and label.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 */
export type StateCountry3 = {
  value: CountryCode;
  /**
   * Name of the country.
   */
  label: string;
}[];

/**
 * Payload to use when using the config field of the Organization on CommerceLayer.
 */
export interface ValidConfigForOrganizationsInCommerceLayer {
  mfe?: {
    default?: MfeConfig;
    [k: string]: MfeConfig | undefined;
  };
  [k: string]: unknown;
}
/**
 * Default settings for links and checkout.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^market:id:[a-zA-Z0-9]*$$".
 */
export interface MfeConfig {
  /**
   * Links for specific micro frontends.
   */
  links?: {
    cart?: Url;
    checkout?: Url;
    identity?: Url;
    microstore?: Url;
    my_account?: Url;
  };
  /**
   * Settings for the Checkout micro front end.
   */
  checkout?: {
    thankyou_page?: Url;
    billing_countries?: StateCountry;
    shipping_countries?: StateCountry1;
    default_country?: CountryCode;
    /**
     * List of states by country with identifier and label.
     */
    billing_states?: {
      [k: string]: StateCountry2;
    };
    /**
     * List of states by country with identifier and label.
     */
    shipping_states?: {
      [k: string]: StateCountry3;
    };
  };
  /**
   * Checkout internal links settings.
   */
  urls?: {
    privacy?: Url;
    terms?: Url;
  };
  /**
   * Default language setting.
   */
  language?: string;
}
